export enum RouteEnums { 
    ADMIN = "/admin",
    INGREDIENT = "/admin/ingredient",
    DIETARY_TAG = "/admin/dietarytag",
    MENU_ITEM = "/admin/menu-item",
    CREATE_INGREDIENT = "/admin/ingredient/create",
    EDIT_INGREDIENT = "/admin/ingredient/edit",
    CREATE_DIETARY_TAG = "/admin/dietarytag/create",
    EDIT_DIETARY_TAG = "/admin/dietarytag/edit",
    CREATE_MENU_ITEM = "/admin/menu-item/create",
    EDIT_MENU_ITEM = "/admin/menu-item/edit",
    SIGN_IN = "/auth/sign-in",
    SIGN_UP = "/auth/register",
    CATEGORY = "/admin/category",
    CREATE_CATEGORY = "/admin/category/create",
    EDIT_CATEGORY = "/admin/category/edit",
    ETHIOPIAN_DISHES = "/ethiopian-dishes",
    FOREIGN_DISHES = "/foreign-dishes",
    PACKAGE = "/admin/package",
    CREATE_PACKAGE = "/admin/package/create",
    EDIT_PACKAGE = "/admin/package/edit",
}