import { store } from "@/store"
import { Provider } from "react-redux"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider store={store}>
      <body>{children}</body>
      </Provider>
    </html>
  )
}
